export const ANXIETY_QUESTIONS = [
  // GAD-7 (0-3 each)
  { id: 'gad1', text: 'Over the past 2 weeks, how often have you been feeling nervous, anxious, or on edge?', options: ['Not at all', 'Several days', 'More than half the days', 'Nearly every day'], scores: [0,1,2,3], screener: 'GAD-7' },
  { id: 'gad2', text: 'How often have you been unable to stop or control your worrying?', options: ['Not at all', 'Several days', 'More than half the days', 'Nearly every day'], scores: [0,1,2,3], screener: 'GAD-7' },
  { id: 'gad3', text: 'How often have you been worrying too much about different things?', options: ['Not at all', 'Several days', 'More than half the days', 'Nearly every day'], scores: [0,1,2,3], screener: 'GAD-7' },
  { id: 'gad4', text: 'How often have you had trouble relaxing?', options: ['Not at all', 'Several days', 'More than half the days', 'Nearly every day'], scores: [0,1,2,3], screener: 'GAD-7' },
  { id: 'gad5', text: 'How often have you been so restless that it was hard to sit still?', options: ['Not at all', 'Several days', 'More than half the days', 'Nearly every day'], scores: [0,1,2,3], screener: 'GAD-7' },
  { id: 'gad6', text: 'How often have you become easily annoyed or irritable?', options: ['Not at all', 'Several days', 'More than half the days', 'Nearly every day'], scores: [0,1,2,3], screener: 'GAD-7' },
  { id: 'gad7', text: 'How often have you felt afraid, as if something awful might happen?', options: ['Not at all', 'Several days', 'More than half the days', 'Nearly every day'], scores: [0,1,2,3], screener: 'GAD-7' },
  // Original (0-2 each)
  { id: 'anx1', text: 'My heart races or I notice physical tension (tight chest, shallow breathing) when I think about upcoming events.', options: ['Rarely or never', 'Sometimes', 'Often'], scores: [0,1,2] },
  { id: 'anx2', text: 'I avoid situations that might make me feel embarrassed or judged by others.', options: ['Rarely or never', 'Sometimes', 'Often'], scores: [0,1,2] },
  { id: 'anx3', text: 'I replay conversations in my head, worrying I said the wrong thing.', options: ['Rarely or never', 'Sometimes', 'Often'], scores: [0,1,2] },
  { id: 'anx4', text: 'I find it hard to fall asleep because my mind will not switch off.', options: ['Rarely or never', 'Sometimes', 'Often'], scores: [0,1,2] },
  { id: 'anx5', text: 'I prepare for worst-case scenarios even when things are going okay.', options: ['Rarely or never', 'Sometimes', 'Often'], scores: [0,1,2] },
  { id: 'anx6', text: 'I feel a sense of dread before social situations like parties, meetings, or calls.', options: ['Rarely or never', 'Sometimes', 'Often'], scores: [0,1,2] },
  { id: 'anx7', text: 'I check things repeatedly (locks, messages, work) because I worry I made a mistake.', options: ['Rarely or never', 'Sometimes', 'Often'], scores: [0,1,2] },
  { id: 'anx8', text: 'I experience sudden waves of intense fear or panic that feel overwhelming.', options: ['Rarely or never', 'Sometimes', 'Often'], scores: [0,1,2] },
  { id: 'anx9', text: 'I cancel plans or decline invitations to avoid the anxiety of showing up.', options: ['Rarely or never', 'Sometimes', 'Often'], scores: [0,1,2] },
  { id: 'anx10', text: 'My worry is so constant that it feels like background noise I cannot turn down.', options: ['Rarely or never', 'Sometimes', 'Often'], scores: [0,1,2] },
  { id: 'anx11', text: 'I feel sweaty, shaky or nauseous in high-pressure or unfamiliar situations.', options: ['Rarely or never', 'Sometimes', 'Often'], scores: [0,1,2] },
  { id: 'anx12', text: 'I ask for reassurance from friends or family more than I would like to.', options: ['Rarely or never', 'Sometimes', 'Often'], scores: [0,1,2] },
  { id: 'anx13', text: 'I feel like I am never truly relaxed — even during leisure time.', options: ['Rarely or never', 'Sometimes', 'Often'], scores: [0,1,2] },
  { id: 'anx14', text: 'I avoid reading news or checking social media because it makes me spiral into worry.', options: ['Rarely or never', 'Sometimes', 'Often'], scores: [0,1,2] },
  { id: 'anx15', text: 'Making a decision feels overwhelming because I am scared of choosing wrong.', options: ['Rarely or never', 'Sometimes', 'Often'], scores: [0,1,2] },
  { id: 'anx16', text: 'I feel on edge in quiet moments, as if something bad is about to happen.', options: ['Rarely or never', 'Sometimes', 'Often'], scores: [0,1,2] },
  { id: 'anx17', text: 'I spend a lot of mental energy trying to control or prevent things I am worried about.', options: ['Rarely or never', 'Sometimes', 'Often'], scores: [0,1,2] },
  { id: 'anx18', text: 'My anxiety has made it harder to focus on work, studies, or conversations.', options: ['Rarely or never', 'Sometimes', 'Often'], scores: [0,1,2] },
]
