export const DEPRESSION_QUESTIONS = [
  // PHQ-9 (0-3 each)
  { id: 'phq1', text: 'Over the past 2 weeks, how often have you had little interest or pleasure in doing things you normally enjoy?', options: ['Not at all', 'Several days', 'More than half the days', 'Nearly every day'], scores: [0,1,2,3], screener: 'PHQ-9' },
  { id: 'phq2', text: 'How often have you been feeling down, low, or hopeless?', options: ['Not at all', 'Several days', 'More than half the days', 'Nearly every day'], scores: [0,1,2,3], screener: 'PHQ-9' },
  { id: 'phq3', text: 'How often have you had trouble falling asleep, staying asleep, or sleeping too much?', options: ['Not at all', 'Several days', 'More than half the days', 'Nearly every day'], scores: [0,1,2,3], screener: 'PHQ-9' },
  { id: 'phq4', text: 'How often have you been feeling tired or like you have very little energy?', options: ['Not at all', 'Several days', 'More than half the days', 'Nearly every day'], scores: [0,1,2,3], screener: 'PHQ-9' },
  { id: 'phq5', text: 'How often have you had a poor appetite, or found yourself eating much more than usual?', options: ['Not at all', 'Several days', 'More than half the days', 'Nearly every day'], scores: [0,1,2,3], screener: 'PHQ-9' },
  { id: 'phq6', text: 'How often have you been feeling bad about yourself — like you have let people down or are not good enough?', options: ['Not at all', 'Several days', 'More than half the days', 'Nearly every day'], scores: [0,1,2,3], screener: 'PHQ-9' },
  { id: 'phq7', text: 'How often have you had trouble concentrating on things, like reading, studying or watching TV?', options: ['Not at all', 'Several days', 'More than half the days', 'Nearly every day'], scores: [0,1,2,3], screener: 'PHQ-9' },
  { id: 'phq8', text: 'How often have you been moving or speaking so slowly that others might notice? Or the opposite — feeling so fidgety or restless that you could not sit still?', options: ['Not at all', 'Several days', 'More than half the days', 'Nearly every day'], scores: [0,1,2,3], screener: 'PHQ-9' },
  { id: 'phq9', text: 'How often have you had thoughts that you would be better off not being here, or thoughts of hurting yourself in any way?', options: ['Not at all', 'Several days', 'More than half the days', 'Nearly every day'], scores: [0,1,2,3], screener: 'PHQ-9', safetyFlag: true },
  // Original items (0-2)
  { id: 'dep1', text: 'I cancel plans with friends or family because I just cannot find the energy to go through with them.', options: ['Rarely or never', 'Sometimes', 'Often'], scores: [0,1,2] },
  { id: 'dep2', text: 'I scroll through social media or watch videos for a long time without really enjoying any of it.', options: ['Rarely or never', 'Sometimes', 'Often'], scores: [0,1,2] },
  { id: 'dep3', text: 'I feel like there is a grey cloud over my day even when nothing specific is wrong.', options: ['Rarely or never', 'Sometimes', 'Often'], scores: [0,1,2] },
  { id: 'dep4', text: 'Getting out of bed in the morning feels like climbing a mountain.', options: ['Rarely or never', 'Sometimes', 'Often'], scores: [0,1,2] },
  { id: 'dep5', text: 'I feel disconnected from people around me, even those I care about.', options: ['Rarely or never', 'Sometimes', 'Often'], scores: [0,1,2] },
  { id: 'dep6', text: 'Things that used to make me excited or curious feel flat or pointless now.', options: ['Rarely or never', 'Sometimes', 'Often'], scores: [0,1,2] },
  { id: 'dep7', text: 'I find myself thinking that nothing will ever really get better.', options: ['Rarely or never', 'Sometimes', 'Often'], scores: [0,1,2] },
  { id: 'dep8', text: 'I have been neglecting basic self-care like eating properly, bathing, or keeping my space tidy.', options: ['Rarely or never', 'Sometimes', 'Often'], scores: [0,1,2] },
  { id: 'dep9', text: 'I feel invisible — like my thoughts and feelings do not really matter to anyone.', options: ['Rarely or never', 'Sometimes', 'Often'], scores: [0,1,2] },
  { id: 'dep10', text: 'Small decisions — like what to eat or what to wear — feel unusually hard to make.', options: ['Rarely or never', 'Sometimes', 'Often'], scores: [0,1,2] },
  { id: 'dep11', text: 'I feel like I am going through the motions of daily life without really being present.', options: ['Rarely or never', 'Sometimes', 'Often'], scores: [0,1,2] },
  { id: 'dep12', text: 'I have been crying more than usual, or felt like crying without a clear reason.', options: ['Rarely or never', 'Sometimes', 'Often'], scores: [0,1,2] },
  { id: 'dep13', text: 'I feel like a burden to the people I love.', options: ['Rarely or never', 'Sometimes', 'Often'], scores: [0,1,2] },
  { id: 'dep14', text: 'My body feels heavy and sluggish even after a full night of sleep.', options: ['Rarely or never', 'Sometimes', 'Often'], scores: [0,1,2] },
  { id: 'dep15', text: 'I look forward to very few things in my day or week.', options: ['Rarely or never', 'Sometimes', 'Often'], scores: [0,1,2] },
  { id: 'dep16', text: 'I feel like the version of me that used to laugh and be carefree has gone missing.', options: ['Rarely or never', 'Sometimes', 'Often'], scores: [0,1,2] },
]
