export const STRESS_QUESTIONS = [
  // PSS-10 (0-4 each; Q4, Q5, Q7, Q8 are reverse scored)
  { id: 'pss1', text: 'In the last month, how often have you been upset because of something that happened unexpectedly?', options: ['Never', 'Almost never', 'Sometimes', 'Fairly often', 'Very often'], scores: [0,1,2,3,4], screener: 'PSS' },
  { id: 'pss2', text: 'In the last month, how often have you felt that you were unable to control the important things in your life?', options: ['Never', 'Almost never', 'Sometimes', 'Fairly often', 'Very often'], scores: [0,1,2,3,4], screener: 'PSS' },
  { id: 'pss3', text: 'In the last month, how often have you felt nervous and stressed?', options: ['Never', 'Almost never', 'Sometimes', 'Fairly often', 'Very often'], scores: [0,1,2,3,4], screener: 'PSS' },
  { id: 'pss4', text: 'In the last month, how often have you felt confident about your ability to handle your personal problems?', options: ['Never', 'Almost never', 'Sometimes', 'Fairly often', 'Very often'], scores: [0,1,2,3,4], screener: 'PSS', reversed: true },
  { id: 'pss5', text: 'In the last month, how often have you felt that things were going your way?', options: ['Never', 'Almost never', 'Sometimes', 'Fairly often', 'Very often'], scores: [0,1,2,3,4], screener: 'PSS', reversed: true },
  { id: 'pss6', text: 'In the last month, how often have you been able to control irritations in your life?', options: ['Never', 'Almost never', 'Sometimes', 'Fairly often', 'Very often'], scores: [0,1,2,3,4], screener: 'PSS' },
  { id: 'pss7', text: 'In the last month, how often have you felt on top of things?', options: ['Never', 'Almost never', 'Sometimes', 'Fairly often', 'Very often'], scores: [0,1,2,3,4], screener: 'PSS', reversed: true },
  { id: 'pss8', text: 'In the last month, how often have you been angered because of things that were outside of your control?', options: ['Never', 'Almost never', 'Sometimes', 'Fairly often', 'Very often'], scores: [0,1,2,3,4], screener: 'PSS', reversed: true },
  { id: 'pss9', text: 'In the last month, how often have you been able to control irritations in your life?', options: ['Never', 'Almost never', 'Sometimes', 'Fairly often', 'Very often'], scores: [0,1,2,3,4], screener: 'PSS' },
  { id: 'pss10', text: 'In the last month, how often have you felt that difficulties were piling up so high that you could not overcome them?', options: ['Never', 'Almost never', 'Sometimes', 'Fairly often', 'Very often'], scores: [0,1,2,3,4], screener: 'PSS' },
  // Original burnout + direction (0-2 each)
  { id: 'str1', text: 'I feel emotionally drained after a typical workday or study session.', options: ['Rarely or never', 'Sometimes', 'Often'], scores: [0,1,2] },
  { id: 'str2', text: 'I feel I know what I am working towards in life.', options: ['Yes, clearly', 'Somewhat', 'Not really'], scores: [0,1,2] },
  { id: 'str3', text: 'I feel numb or detached at the end of a workday.', options: ['Rarely or never', 'Sometimes', 'Often'], scores: [0,1,2] },
  { id: 'str4', text: 'I have lost the sense of purpose I used to feel about my work or studies.', options: ['Rarely or never', 'Sometimes', 'Often'], scores: [0,1,2] },
  { id: 'str5', text: 'I feel like I am running on empty — pushing through but not really present.', options: ['Rarely or never', 'Sometimes', 'Often'], scores: [0,1,2] },
  { id: 'str6', text: 'I find it hard to feel enthusiastic about the future.', options: ['Rarely or never', 'Sometimes', 'Often'], scores: [0,1,2] },
  { id: 'str7', text: 'I take on more than I can handle because I find it hard to say no.', options: ['Rarely or never', 'Sometimes', 'Often'], scores: [0,1,2] },
  { id: 'str8', text: 'I feel resentful toward people or tasks that demand my time and energy.', options: ['Rarely or never', 'Sometimes', 'Often'], scores: [0,1,2] },
  { id: 'str9', text: 'I have a clear sense of my values and what matters most to me.', options: ['Yes, clearly', 'Somewhat', 'Not really'], scores: [0,1,2] },
  { id: 'str10', text: 'I struggle to switch off and relax, even during weekends or holidays.', options: ['Rarely or never', 'Sometimes', 'Often'], scores: [0,1,2] },
  { id: 'str11', text: 'I feel like I am just going through the motions without a real sense of direction.', options: ['Rarely or never', 'Sometimes', 'Often'], scores: [0,1,2] },
  { id: 'str12', text: 'Small setbacks feel catastrophic and hard to recover from.', options: ['Rarely or never', 'Sometimes', 'Often'], scores: [0,1,2] },
  { id: 'str13', text: 'I feel physically tense (headaches, neck pain, jaw clenching) from stress.', options: ['Rarely or never', 'Sometimes', 'Often'], scores: [0,1,2] },
  { id: 'str14', text: 'I feel proud of the direction my life is heading.', options: ['Yes, mostly', 'Somewhat', 'Not really'], scores: [0,1,2] },
  { id: 'str15', text: 'I feel like I am moving forward in life, not just standing still.', options: ['Yes, mostly', 'Somewhat', 'Not really'], scores: [0,1,2] },
]
